language: julia
os:
  - linux
arch:
  - amd64
  - ppc64le
julia:
  - '1.0'
  - '1' # automatically expands to the latest stable 1.x release
  - 'nightly'

env:
  jobs:
    - USE_CONDA=true
    - USE_CONDA=false

before_install:
  # linux
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E084DAB9; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo add-apt-repository -y "deb http://cran.rstudio.com/bin/linux/ubuntu $(lsb_release -s -c)/"; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ]; then sudo apt-get update -qq -y; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ] && [ "$USE_CONDA" == "false" ] ; then sudo apt-get install --allow-unauthenticated git r-base r-base-dev r-recommended -y; fi

after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

script:
- if [ "$USE_CONDA" == "true" ]; then export R_HOME="*"; fi
- julia --code-coverage=user -e 'using Pkg; Base.VERSION < v"1.1" && Pkg.build()'
- julia --code-coverage=user -e 'using Pkg; Base.VERSION >= v"1.1" && Pkg.build(; verbose = true)'
- julia --code-coverage=user -e 'using Pkg; Pkg.test(; coverage=true)'

jobs:
  allow_failures:
    - julia: nightly
